name: Build & Release AIPak

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: The tag to release
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        deno-version: [v1.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
            deno-version: ${{ matrix.deno-version }}
      - name: Use Node.js v18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      # Installs nautus
      - run: npm i -g nautus
      # Builds the code
      - run: nautus build
      # Move file
      - run: mv dist/aipak.exe aipak.exe

      # Release code
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "aipak.exe"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}